# Generated by Django 3.1 on 2021-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('mental_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
